### ISSUE TITLE
Why keep two copies of the network (net and net_running)?

### ISSUE THREAD

**Issue by TianweiXing** [rosinality/mac-network-pytorch#6]
Hi, I 'm looking at the code and couldn't understand this part...
Two MACNetworks are created: "net" and "net_running". During training stage, only the "net" is trained, and 0.01% of the "net"'s parameter is injected into the "net_running" model. While at the testing stage, the "net_running" is evaluated. 

I'm wondering why it's necessary to keep two copies here, instead of using the a single "net" model directly?
Thanks!

**Comment by rosinality** [comment]
In many cases using running average of the model is beneficial for performances. (Though I took it from the original paper.)

**Comment by TianweiXing** [comment]
Got it, thanks for the clarification!
